# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: my_variable
  value: one

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo ${MY_VARIABLE}
    echo ${MY_VARIABLE_2}
    echo ${MY_VARIABLE_3}
    echo '##vso[task.setvariable variable=one]firstValue'
    echo '##vso[task.setvariable variable=two]secondValue'
    echo '##vso[task.setvariable variable=onesecondValue]thirdValue'
    echo $ONE
    
  displayName: 'Run a script'

- script: |
    echo $(two)
    echo $(one)
    echo $(onesecondValue)
    echo $ONE

  displayName: 'Run a multi-line script'
